#!/bin/bash
# Launch the dedicated SANDBOX API (issue #51): isolated container on :11420
# (1PESI band, was 8089 — direct swap, the stack was down at migration) with
# the SANDBOX Polar secret (deploy/sandbox.env), a throwaway ops db (confinia_sbx
# The BILLING_* amounts also come from sandbox.env, and ONLY from there: the
# tariff is configuration in the same sense the secrets are (RULES 19), and
# leaving them unset keeps every tier on the old flat behaviour.
# in the ops-db instance) and the active color's geo db (read-only). Sandbox
# only — test cards, no real fees. Run ON THE VM after rsync.
set -eu
cd "$(dirname "$0")/.."
PGPW=$(grep '^POSTGRES_PASSWORD=' deploy/secrets.env | cut -d= -f2)
set -a; . deploy/sandbox.env; [ -r deploy/creem.env ] && . deploy/creem.env; set +a
ACTIVE=$(cat ~/confinia-edge-state/ACTIVE_COLOR)
podman exec confinia_ops-db_1 psql -U confinia -d confinia -tc \
  "SELECT 1 FROM pg_database WHERE datname='confinia_sbx'" | grep -q 1 || \
  podman exec confinia_ops-db_1 psql -U confinia -d confinia -c 'CREATE DATABASE confinia_sbx OWNER confinia'
# No `rm -f || true` here: it swallowed its own failure, the run that
# followed collided on the name, and the environment stayed on the OLD
# container -- a deploy that had run and changed nothing. --replace is
# atomic and cannot half-succeed.
# The sandbox joins the ACTIVE COLOUR'S NETWORK, and reaches both databases by
# container name — it does NOT run on the host network.
#
# It used to. That worked only while the ops database still published
# 0.0.0.0:5440; the platform audit removed that publish on 2026-08-12, and a
# --network host container has no route left to a name that only resolves
# inside a podman network. The sandbox happened to be stopped that day, so the
# breakage surfaced only when it was next started, as a startup that hung
# forever on "Waiting for application startup" — no error, no exit.
#
# The DSN comment was already right about WHY a container name is needed; the
# network the container ran on made it impossible to honour.
#
# `db` is the colour's own alias on that network, so the sandbox reads whichever
# geo database the active colour serves, with no host port involved.
#
# Keycloak lives on confinia_default, so the sandbox joins that network too and
# reaches it by name. Not through host.containers.internal: Keycloak publishes on
# 127.0.0.1:11070, and the host GATEWAY address is not the host's loopback, so that
# route is refused -- the same distinction that made the ops database unreachable.
# (Comment kept out of the podman run: a # line inside a backslash
# continuation ends the command and the remaining -e flags ran as their
# own commands — the script could not work as committed.)
# SYSTEMD, not a bare `podman run` (issue #123, third bite). A container
# created here is a child of whatever ran this script -- when that is a CI
# job, conmon dies with the job and leaves a wedged corpse that the NEXT
# deploy's --replace cannot remove ("conmon exited prematurely ... internal
# libpod error", exit 125). Staging got this treatment in #199; the sandbox
# kept wedging deployments until it got the same.
#
# The env goes in a 600 FILE, never Environment= lines: a Quadlet Environment=
# value lands on the service command line, which systemctl status prints and
# the journal keeps -- the #202 password leak, one service over.
UNIT_DIR="$HOME/.config/containers/systemd"
mkdir -p "$UNIT_DIR"
umask 077
cat > "$UNIT_DIR/confinia-sbx.env" <<ENVF
PG_DSN=postgresql://confinia:${PGPW}@db:5432/confinia
OPS_DSN=postgresql://confinia:${PGPW}@confinia_ops-db_1:5432/confinia_sbx
VISITOR_SALT_SECRET=sbx-salt
POLAR_WEBHOOK_SECRET=${POLAR_WEBHOOK_SECRET}
POLAR_PRODUCT_PRO=${POLAR_PRODUCT_PRO}
POLAR_PRODUCT_ENTERPRISE=${POLAR_PRODUCT_ENTERPRISE}
POLAR_API_BASE=https://sandbox-api.polar.sh
POLAR_ACCESS_TOKEN=${POLAR_ACCESS_TOKEN:-}
CREEM_WEBHOOK_SECRET=${CREEM_WEBHOOK_SECRET:-}
CREEM_TIERS=${CREEM_TIERS:-[]}
CREEM_MODE=${CREEM_MODE:-test}
BILLING_FLOOR_CENTS=${BILLING_FLOOR_CENTS:-0}
BILLING_PER_REPORT_CENTS=${BILLING_PER_REPORT_CENTS:-0}
BILLING_CAP_CENTS=${BILLING_CAP_CENTS:-0}
KC_ISSUER=https://sandbox.confinia.io/auth/realms/confinia-sbx
KC_DISCOVERY=http://confinia_keycloak_1:8180/auth/realms/confinia-sbx
ENVF
chmod 600 "$UNIT_DIR/confinia-sbx.env"

cat > "$UNIT_DIR/confinia-sbx-api.container" <<UNIT
# GENERATED by deploy/sandbox-up.sh -- rewritten on every deploy to follow the
# active colour ($ACTIVE as of $(date -u +%FT%TZ)).
[Unit]
Description=Confinia sandbox API
After=network-online.target

[Container]
ContainerName=confinia-sbx_api
Image=localhost/confinia-api:latest
Network=confinia-${ACTIVE}_default
Network=confinia_default
PublishPort=127.0.0.1:11420:8000
EnvironmentFile=%h/.config/containers/systemd/confinia-sbx.env
Exec=python -m uvicorn main:app --host 0.0.0.0 --port 8000

[Service]
Restart=always
RestartSec=10
StartLimitBurst=5
StartLimitIntervalSec=300

[Install]
WantedBy=default.target
UNIT
systemctl --user daemon-reload
# Clear any wedged predecessor: retry the removal, reset the unit, one wedged
# retry on the restart -- a deploy must outlive one broken container.
for _ in 1 2 3; do
	podman rm -f --ignore confinia-sbx_api >/dev/null 2>&1 && break
	sleep 3
done
systemctl --user reset-failed confinia-sbx-api 2>/dev/null || true
if ! systemctl --user restart confinia-sbx-api; then
	podman rm -f --ignore confinia-sbx_api >/dev/null 2>&1 || true
	systemctl --user reset-failed confinia-sbx-api 2>/dev/null || true
	systemctl --user restart confinia-sbx-api
fi
for _ in $(seq 1 30); do
	curl -sf --max-time 3 http://127.0.0.1:11420/healthz >/dev/null 2>&1 && break
	sleep 2
done
curl -sf http://127.0.0.1:11420/healthz && echo " sandbox API up on :11420"
