#!/bin/bash
# Orchestrator of the COLOR stacks (blue/green, complete; doctrine: the geo
# database is an artifact rebuilt by double ingestion, never copied). VM.
#   ./deploy/stacks.sh up-db <blue|green>   # starts the color's geo db
#   ./deploy/stacks.sh build <blue|green>   # double ingestion IN THE BACKGROUND
#                                           # (log: ~/logs/build-geo-<c>.log)
#   ./deploy/stacks.sh status               # state of both colors
# The cutover of the color APIs (replacing the historical api/api-b
# containers with the stacks' api services) happens once a build is
# validated: see build TODO "stacks workstream".
set -eu
cd "$(dirname "$0")/.."

pc() {	# $1 = color, rest = podman-compose command
	local c="$1"; shift
	# One EXPLICIT compose file per color (founder's choice);
	# absolute path (podman-compose and relative paths: known trap).
	podman-compose -p "confinia-$c" -f "$PWD/deploy/stack/docker-compose-$c.yml" "$@"
}

case "${1:-}" in
up-db)
	c="${2:?color}"
	pc "$c" up -d db
	;;
build)
	c="${2:?color}"
	mkdir -p ~/logs
	nohup ./deploy/build-geo.sh "$c" > ~/logs/"build-geo-$c.log" 2>&1 &
	echo "build $c started in the background: tail -f ~/logs/build-geo-$c.log"
	;;
# Writes the caddy upstreams state file: active color first for the
# public, and the DEDICATED STAGING STACK (:11320) for staging, with the passive
# colour as fallback so staging still answers if that stack is down.
# Staging stopped BEING the passive colour on 2026-08-12 (issue #113): it was
# both the thing you exercise and the thing production rolls back to, so a
# staging test wrote into production's operational tables and could consume a
# paying customer's quota.
# The old 8093 "data slot" is GONE: that port is BURNED (held by the maplibre
# tenant). Keeping it first in the staging upstreams meant caddy probed another
# product's service on every staging request, and would have proxied our traffic
# there had it ever answered 2xx on /healthz.
write-upstreams|promote)
	c="${2:?active color (blue|green)}"
	# A promotion changes what production serves, so it must ship code that has
	# been reviewed. This directory is BOTH the deployment checkout and the tree
	# people edit in: deploy-staging resets it to the commit it deploys, and
	# promote-production does not -- it runs whatever is sitting here. On
	# 2026-08-24 that meant a production promotion executed scripts from an
	# unmerged branch. Nothing broke, and nothing would have said so.
	#
	# write-upstreams is exempt: deploy-edge.sh calls it to regenerate the state
	# file, which changes no colour.
	#
	# PROMOTE_UNSHIPPED=1 overrides. A rollback runs through this same path, and
	# a guard that blocks a rollback during an incident is worse than the hazard
	# it guards against.
	if [ "$1" = promote ] && [ "${PROMOTE_UNSHIPPED:-0}" != 1 ]; then
		if ! git diff --quiet HEAD --; then
			echo "REFUSING: tracked files are modified in $PWD." >&2
			git --no-pager diff --stat HEAD -- >&2
			echo "A promotion would ship them. Commit, or PROMOTE_UNSHIPPED=1." >&2
			exit 3
		fi
		git fetch -q origin main 2>/dev/null \
			|| echo "  [!] could not reach origin; checking against the last known origin/main" >&2
		if ! git merge-base --is-ancestor HEAD origin/main; then
			echo "REFUSING: HEAD $(git rev-parse --short HEAD) is not on origin/main." >&2
			echo "  this checkout is on $(git rev-parse --abbrev-ref HEAD) -- promoting" >&2
			echo "  would put unreviewed code live. PROMOTE_UNSHIPPED=1 to override." >&2
			exit 3
		fi
		echo "  promoting $(git rev-parse --short HEAD), which is on origin/main"
	fi
	case "$c" in
		# Blue is still on its legacy port: it is the ACTIVE colour and cannot be
		# recreated onto 11120 before the founder's promotion. Green is 11220 only,
		# its legacy 8402 having been dropped at step 4. Getting this pair wrong
		# does not fail loudly -- caddy just has one dead upstream and falls back,
		# so production stays up while its safety net is gone.
		blue)  ACT=11120; PAS=11220 ;;
		green) ACT=11220; PAS=11120 ;;
		*) echo "unknown color: $c" >&2; exit 2 ;;
	esac
	mkdir -p ~/confinia-edge-state
	# Staging auth as LITERALS in the state file (caddy's admin reload does
	# not resolve {env.*} placeholders, unlike startup).
	SU=$(grep '^STAGING_USER=' deploy/secrets.env | cut -d= -f2-)
	SH=$(grep '^STAGING_HASH=' deploy/secrets.env | cut -d= -f2-)
	printf '(staging_auth) {\n\tbasic_auth {\n\t\t%s %s\n\t}\n}\n' "$SU" "$SH" \
		> ~/confinia-edge-state/auth.caddy
	cat > ~/confinia-edge-state/upstreams.caddy <<CADDY
# GENERATED by deploy/stacks.sh promote: active color = $c ($(date -u +%FT%TZ))
(api_upstreams) {
	reverse_proxy 127.0.0.1:$ACT 127.0.0.1:$PAS {
		lb_policy first
		lb_try_duration 5s
		lb_try_interval 250ms
		fail_duration 15s
		unhealthy_status 5xx
		health_uri /healthz
		health_interval 10s
		health_timeout 3s
	}
}
# Which colour is serving production, for the platform dashboard. Emitted at
# the PROXY rather than by the app, so it still appears on a 302, a 401 or a
# 500 -- the moments you most want to know which colour answered. Written from
# the same \$c as the ports above and in the same heredoc: a header that says
# blue while green serves is worse than none, it makes the dashboard a
# confident liar.
(active_colour) {
	header X-Active-Colour "$c"
}
(staging_upstreams) {
	reverse_proxy 127.0.0.1:11320 127.0.0.1:$PAS {
		lb_policy first
		lb_try_duration 5s
		lb_try_interval 250ms
		fail_duration 15s
		health_uri /healthz
		health_interval 10s
		health_timeout 3s
	}
}
CADDY
	# Which demo the public sees. Written here and nowhere else: the demo now
	# changes on PROMOTION, like the API, instead of the moment a merge reached
	# the checkout. If the colour root has not been staged yet, keep serving the
	# checkout rather than a directory that may be empty.
	if [ -d "$HOME/demo-$c" ] && [ -e "$HOME/demo-$c/index.html" ]; then
		DEMO_ROOT="/srv/demo-$c"
	else
		DEMO_ROOT="/srv/demo"
		echo "  [!] ~/demo-$c not staged yet -- demo still served from the checkout" >&2
	fi
	printf '# GENERATED by deploy/stacks.sh promote (%s)\n(demo_root) {\n\troot * %s\n}\n' \
		"$(date -u +%FT%TZ)" "$DEMO_ROOT" > ~/confinia-edge-state/demo.caddy
	echo "$c" > ~/confinia-edge-state/ACTIVE_COLOR
	# Active-color MARKER file (issue #85): exactly one active-<color> file
	# exists; the otel collector (filestats) turns it into the Grafana
	# "which color is PROD" panel, its mtime = last promotion time.
	rm -f ~/confinia-edge-state/active-blue ~/confinia-edge-state/active-green
	touch ~/confinia-edge-state/"active-$c"
	podman run --rm --env-file deploy/secrets.env 		-v "$PWD/deploy/caddy:/etc/caddy:ro" 		-v "$HOME/confinia-edge-state:/etc/caddy/active:ro" 		docker.io/library/caddy:2 caddy validate --config /etc/caddy/Caddyfile >/dev/null
	podman exec confinia_caddy_1 caddy reload --config /etc/caddy/Caddyfile
	echo "OK: active color = $c (public on $ACT, staging on $PAS)"
	;;
status)
	echo "active color: $(cat ~/confinia-edge-state/ACTIVE_COLOR 2>/dev/null || echo 'not set (legacy)')"
	for c in blue green; do
		db="confinia-${c}_db_1"
		if podman exec "$db" pg_isready -U confinia >/dev/null 2>&1; then
			n=$(podman exec "$db" psql -U confinia -d confinia -t -A -c \
				"SELECT count(*) FROM commune_version" 2>/dev/null || echo "schema missing")
			echo "$c: db up, commune_version = $n"
		else
			echo "$c: db down"
		fi
	done
	;;
*)
	echo "usage: $0 [up-db <c> | build <c> | status]" >&2
	exit 2
	;;
esac
