#!/bin/bash
# Orchestrator of the COLOR stacks (blue/green, complete; doctrine: the geo
# database is an artifact rebuilt by double ingestion, never copied). VM.
#   ./deploy/stacks.sh up-db <blue|green>   # starts the color's geo db
#   ./deploy/stacks.sh build <blue|green>   # double ingestion IN THE BACKGROUND
#                                           # (log: ~/logs/build-geo-<c>.log)
#   ./deploy/stacks.sh status               # state of both colors
# The cutover of the color APIs (replacing the historical api/api-b
# containers with the stacks' api services) happens once a build is
# validated: see build TODO "stacks workstream".
set -eu
cd "$(dirname "$0")/.."

pc() {	# $1 = color, rest = podman-compose command
	local c="$1"; shift
	# One EXPLICIT compose file per color (founder's choice);
	# absolute path (podman-compose and relative paths: known trap).
	podman-compose -p "confinia-$c" -f "$PWD/deploy/stack/docker-compose-$c.yml" "$@"
}

case "${1:-}" in
up-db)
	c="${2:?color}"
	pc "$c" up -d db
	;;
build)
	c="${2:?color}"
	mkdir -p ~/logs
	nohup ./deploy/build-geo.sh "$c" > ~/logs/"build-geo-$c.log" 2>&1 &
	echo "build $c started in the background: tail -f ~/logs/build-geo-$c.log"
	;;
# Writes the caddy upstreams state file: active color first for the
# public, passive (+8002 data) for staging. Then graceful reload.
write-upstreams|promote)
	c="${2:?active color (blue|green)}"
	case "$c" in
		blue)  ACT=8000; PAS=8001 ;;
		green) ACT=8001; PAS=8000 ;;
		*) echo "unknown color: $c" >&2; exit 2 ;;
	esac
	mkdir -p ~/confinia-edge-state
	# Staging auth as LITERALS in the state file (caddy's admin reload does
	# not resolve {env.*} placeholders, unlike startup).
	SU=$(grep '^STAGING_USER=' deploy/secrets.env | cut -d= -f2-)
	SH=$(grep '^STAGING_HASH=' deploy/secrets.env | cut -d= -f2-)
	printf '(staging_auth) {\n\tbasic_auth {\n\t\t%s %s\n\t}\n}\n' "$SU" "$SH" \
		> ~/confinia-edge-state/auth.caddy
	cat > ~/confinia-edge-state/upstreams.caddy <<CADDY
# GENERATED by deploy/stacks.sh promote: active color = $c ($(date -u +%FT%TZ))
(api_upstreams) {
	reverse_proxy 127.0.0.1:$ACT 127.0.0.1:$PAS {
		lb_policy first
		lb_try_duration 5s
		lb_try_interval 250ms
		fail_duration 15s
		unhealthy_status 5xx
		health_uri /healthz
		health_interval 10s
		health_timeout 3s
	}
}
(staging_upstreams) {
	reverse_proxy 127.0.0.1:8002 127.0.0.1:$PAS {
		lb_policy first
		lb_try_duration 5s
		lb_try_interval 250ms
		fail_duration 15s
		health_uri /healthz
		health_interval 10s
		health_timeout 3s
	}
}
CADDY
	echo "$c" > ~/confinia-edge-state/ACTIVE_COLOR
	podman run --rm --env-file deploy/secrets.env 		-v "$PWD/deploy/caddy:/etc/caddy:ro" 		-v "$HOME/confinia-edge-state:/etc/caddy/active:ro" 		docker.io/library/caddy:2 caddy validate --config /etc/caddy/Caddyfile >/dev/null
	podman exec confinia_caddy_1 caddy reload --config /etc/caddy/Caddyfile
	echo "OK: active color = $c (public on $ACT, staging on 8002 then $PAS)"
	;;
status)
	echo "active color: $(cat ~/confinia-edge-state/ACTIVE_COLOR 2>/dev/null || echo 'not set (legacy)')"
	for c in blue green; do
		db="confinia-${c}_db_1"
		if podman exec "$db" pg_isready -U confinia >/dev/null 2>&1; then
			n=$(podman exec "$db" psql -U confinia -d confinia -t -A -c \
				"SELECT count(*) FROM commune_version" 2>/dev/null || echo "schema missing")
			echo "$c: db up, commune_version = $n"
		else
			echo "$c: db down"
		fi
	done
	;;
*)
	echo "usage: $0 [up-db <c> | build <c> | status]" >&2
	exit 2
	;;
esac
