#!/bin/bash
# Bring up the dedicated STAGING stack (issue #113).
#
#   ./deploy/staging-up.sh     # (re)start staging against the passive colour
#
# Staging is no longer the passive colour. Until 2026-08-12 it WAS, which made
# it two things at once: the environment you exercise and the one production
# rolls back to. So a staging test wrote into production's operational tables --
# api_usage, premium_seen, api_key -- and could consume a paying customer's
# quota. The API creates its tables on boot, so a schema change tried on staging
# was applied to the PRODUCTION ops database the moment the container started.
#
# SEPARATE : the operational database (its own `confinia_staging`), the identity
#            realm (confinia-sbx), the billing mode (Polar test).
# SHARED   : the passive colour's geo database, READ-ONLY in practice -- it is a
#            build artefact and every write in api/main.py targets OPS_DSN.
#            tests/test_staging_isolation.py asserts that premise still holds.
#
# PORT 11320 is confinia's 1PESI slot: confinia(1) staging(3) api(2) main(0).
# It was 8403 (our 84xx band) until the legacy drop, and 8501 for a few hours on
# 2026-08-12 -- self-assigned from a band I had only checked was FREE, not
# whether it was MINE. 85xx belongs to panoramax. "Free" is not "available",
# which is exactly the reasoning that cost us 8092: another tenant checked the
# same way. If 11xxx ever fills up, request an extension via confinia/platform.
# Never self-assign.
#
# The ops database is reached BY CONTAINER NAME, not through a published host
# port. Proven on 2026-08-12: confinia_ops-db_1 resolves on the colour network
# and answers on 5432, so nothing needs to be exposed on the host at all. The
# colour APIs and Keycloak were moved the same way on 2026-08-12, and the
# database no longer publishes a host port at all.
#
# Uses `podman run` rather than compose, following deploy/sandbox-up.sh: the
# container must join the PASSIVE colour's network to reach its database, and
# which colour that is changes at every promotion. RE-RUN THIS AFTER A PROMOTION.
set -eu
cd "$(dirname "$0")/.."

PORT=11320   # 1PESI: confinia(1) · staging(3) · api(2) · main(0)
NAME=confinia-staging_api_1
OPS_DB=confinia_staging

active() { cat ~/confinia-edge-state/ACTIVE_COLOR 2>/dev/null || echo blue; }
PASSIVE=$([ "$(active)" = blue ] && echo green || echo blue)
NET="confinia-${PASSIVE}_default"

PW=$(grep '^POSTGRES_PASSWORD=' deploy/secrets.env | cut -d= -f2-)

echo "== staging reads the geo database of the PASSIVE colour ($PASSIVE, network $NET)"
echo "== staging writes to its OWN operational database ($OPS_DB)"

# Its own database, created once. The API builds its schema on boot, which is
# also precisely why pointing it at the production database was so damaging.
podman exec confinia_ops-db_1 psql -U confinia -d postgres -tAc \
	"SELECT 1 FROM pg_database WHERE datname='${OPS_DB}'" | grep -q 1 \
	|| podman exec confinia_ops-db_1 createdb -U confinia "${OPS_DB}"

# The guard from #123: never destroy a working container for a port we cannot
# get back.
for p in "$PORT"; do
	if ss -ltn 2>/dev/null | grep -qE "127\.0\.0\.1:$p " \
	   && ! podman ps --format '{{.Names}}' | grep -qx "$NAME"; then
		echo "REFUSING: 127.0.0.1:$p is held by something that is not $NAME" >&2
		exit 1
	fi
done

# SYSTEMD, not a bare `podman run` (issue #123). A container created here is a
# child of whatever ran this script -- and when that is a CI job, its rootless
# port forwarder dies with the job. The symptom is precise and misleading:
# `podman ps` keeps showing `127.0.0.1:11320->8000/tcp` while `ss` shows nothing
# listening, so the environment looks deployed and answers nothing. That is how
# the founder got a 17-hour-old staging build three times.
#
# The unit is GENERATED rather than committed, because staging follows the
# PASSIVE colour and that changes at every promotion -- a static unit would pin
# yesterday's network and read the wrong colour's database.
UNIT_DIR="$HOME/.config/containers/systemd"
mkdir -p "$UNIT_DIR"

# The DSNs go in a 600 file, NEVER as Environment= lines. A Quadlet unit's
# Environment= values become `podman run --env ...` on the service command line,
# which `systemctl status` prints and the journal keeps -- so the database
# password ends up readable by anything that can read the journal, and pasted
# into every terminal that asks about the service. That is how the freshly
# rotated password leaked on 2026-08-17.
umask 077
cat > "$UNIT_DIR/confinia-staging.env" <<ENVF
PG_DSN=postgresql://confinia:${PW}@db:5432/confinia
OPS_DSN=postgresql://confinia:${PW}@confinia_ops-db_1:5432/${OPS_DB}
ENVF
chmod 600 "$UNIT_DIR/confinia-staging.env"
cat > "$UNIT_DIR/confinia-staging-api.container" <<UNIT
# GENERATED by deploy/staging-up.sh -- do not edit, it is rewritten on every
# deploy to follow the passive colour ($NET as of $(date -u +%FT%TZ)).
[Unit]
Description=Confinia staging API
After=network-online.target

[Container]
ContainerName=$NAME
Image=localhost/confinia-api:latest
Network=$NET
PublishPort=127.0.0.1:${PORT}:8000
EnvironmentFile=%h/projects/confinia/deploy/secrets.env
EnvironmentFile=%h/.config/containers/systemd/confinia-staging.env
Environment=KC_ISSUER=https://www.confinia.io/auth/realms/confinia-sbx
Environment=OTEL_EXPORTER_OTLP_ENDPOINT=http://host.containers.internal:11060
Environment=POLAR_MODE=sandbox
Environment=CONFINIA_ENV=staging

[Service]
Restart=always
RestartSec=10
StartLimitBurst=5
StartLimitIntervalSec=300

[Install]
WantedBy=default.target
UNIT
systemctl --user daemon-reload
# The old container must be gone before systemd creates its own -- and podman
# sometimes wedges a container in a state `rm -f` cannot clear on the first
# try ("conmon exited prematurely ... internal libpod error", which failed a
# whole deployment on 2026-08-18). Retry, then reset the unit's failure state:
# a deploy must outlive one wedged container.
for _ in 1 2 3; do
	podman rm -f --ignore "$NAME" >/dev/null 2>&1 && break
	sleep 3
done
systemctl --user reset-failed confinia-staging-api 2>/dev/null || true
if ! systemctl --user restart confinia-staging-api; then
	# One wedged retry: clear again and try once more before giving up loudly.
	podman rm -f --ignore "$NAME" >/dev/null 2>&1 || true
	systemctl --user reset-failed confinia-staging-api 2>/dev/null || true
	systemctl --user restart confinia-staging-api
fi

for i in $(seq 1 60); do
	curl -sf --max-time 3 "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1 && {
		echo "OK: staging on :$PORT — try https://staging.api.confinia.io"; exit 0; }
	sleep 2
done
echo "FAILURE: /healthz on $PORT not responding after 120 s" >&2
podman logs --tail 15 "$NAME" >&2 || true
exit 1
