if (!requireNamespace("confinia", quietly = TRUE))
  for (f in list.files("clients/r/confinia/R", full.names = TRUE)) source(f)
cli <- confinia()
u <- unit_at(cli, lat = 48.85, lon = 2.35, at = "2020-06-01")
stopifnot(nrow(u) == 1, u$country == "FR"); cat("unit_at OK:", u$nom, "\n")
p <- passage(cli, "01091", date_from = "2018-06-01", date_to = "2020-06-01")
stopifnot(any(p$code == "01033")); cat("passage OK\n")
a <- attributions(cli); stopifnot(any(a$source == "insee-cog")); cat("attributions OK\n")
cat("R CLIENT SMOKE PASSED\n")
